DROP SCHEMA PUBLIC CASCADE;
CREATE SCHEMA PUBLIC;

CREATE TABLE profile (
  id BIGSERIAL PRIMARY KEY,
  license VARCHAR(36) UNIQUE NOT NULL,
  email_address VARCHAR UNIQUE NOT NULL,
  pin VARCHAR(7) NOT NULL,
  name VARCHAR NOT NULL,
  activated BIGINT NOT NULL,
  deactivated BIGINT NOT NULL
);

CREATE TABLE fault (
  id BIGSERIAL PRIMARY KEY,
  profile_id BIGINT REFERENCES profile(id),
  cause VARCHAR NOT NULL,
  occurred BIGINT NOT NULL
);